export const HOST = "http://95.111.75.178:8080"

export const USER_TYPE = {
    GUEST: 'GUEST', 
    REGISTERED_USER: 'REGISTERED_USER', 
    RESTAURANT_OWNER: 'RESTAURANT_OWNER', 
    MODERATOR: 'MODERATOR', 
    ADMIN: 'ADMIN',
}